# Generated by Django 2.1 on 2018-08-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=100)),
                ('user_agent', models.TextField(default='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=10)),
                ('index', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=20)),
                ('display_name_en', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=200)),
                ('givenname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=500)),
                ('password_md5', models.CharField(default='', max_length=200)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Grade')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('session_number', models.IntegerField(default=-1)),
                ('program_number', models.IntegerField(default=-1)),
                ('session_category', models.CharField(default='', max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_liked', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Participant')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_cancelled', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Participant')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Participant'),
        ),
    ]
