# Generated by Django 2.1 on 2018-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20180810_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='session_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
